### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by axsaucedo** [cloud-mes/demo#2]
After installing the bundles (from the latest ones in the gem repo) I tried running the commands in the README.md file, but I get the following error:

``` bash
Exiting
/Users/FOLDER/Programming/devnull/cloud-mes/demo/config/routes.rb:5:in `block in <top (required)>': uninitialized constant Mes::Core (NameError)
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config/routes.rb:1:in `<top (required)>'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/file_update_checker.rb:77:in `execute'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
    from /Users/FOLDER/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config/environment.rb:5:in `<top (required)>'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config.ru:3:in `require'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config.ru:3:in `block in <main>'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config.ru:in `new'
    from /Users/FOLDER/Programming/devnull/cloud-mes/demo/config.ru:in `<main>'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:59:in `app'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:124:in `log_to_stdout'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:77:in `start'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `server'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/FOLDER/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by axsaucedo** [comment]
The pull request I submitted contains the code I used to run this - it's exactly the same, the only difference is that I changed this:
``` ruby
gem 'cloud-mes', path: '../cloud-mes'
gem 'mes-core', path: '../cloud-mes/core'
gem 'mes-modeler', path: '../cloud-mes/modeler'
gem 'mes-data-semi', path: '../cloud-mes-data-semi'
```
**into this:**
``` ruby
gem 'cloud-mes'
gem 'mes-core'
gem 'mes-modeler'
gem 'mes-data-semi'
```
